### ISSUE TITLE
Node vs Bucket metrics

### ISSUE THREAD

**Issue by shipmak** [blakelead/couchbase_exporter#6]
I have a 3 node cluster.  I'm wondering do I need a separate exporter for each and every node to grab each "NODE's" metrics (for example:  cb_node_stats_cmd_get)? If my understanding is correct, each exporter would be calculating the same BUCKET and CLUSTER metrics redundantly. 

Is there a way to just have 1 exporter running that points to a single node in the cluster, and then can identify all other nodes in that cluster and provide the *NODE metrics breakdown for each node?  (Much like we have for BUCKETs, if we have multiple buckets, we report on each bucket from a single exporter).

**Comment by blakelead** [comment]
Thanks for your question.

The answer can be found in the "Deployment" paragraph of [Prometheus documentation](https://prometheus.io/docs/instrumenting/writing_exporters/#deployment).

For the sake of following good practices, I made node metrics specific to the node that is being scraped hence the need to deploy an exporter instance for each node.

As for redundancy I cannot give you an definite answer right now, but I'll try it as soon as I can.

**Comment by blakelead** [comment]
I tested it and I have the same cluster metrics for each instance. I also tested some other exporters like [Elasticsearch Exporter](https://github.com/justwatchcom/elasticsearch_exporter) and same thing happens.

I don't know what to think about that... Anyway, if it is really annoying to use, I could implement a way to have only one instance of the exporter that scrapes all the nodes metrics.

**Comment by blakelead** [comment]
I will close this issue, but feel free to react if you feel that this issue should be treated.

**Comment by nemmyam** [comment]
Hi,
I encountered the same issue here.
I have read your answer to @shipmak and I read the prometheus Deployment paragraph but I think this should be an exception here. since I have 6 nodes cluster (others might have more) I don't think it makes sense to have 6 deployments running only with different nodes variables, plus the redundant "Bucket" metrics DO mess up your queries ones you start sum up things and forget about the "instance" label..
I feel like the best solution for this is a "self discover" mechanism for each node in the cluster and report them all as a label.
For example instead of:
cb_node_service_up 1 =>  
cb_node_service_up{node="node1"} 1
cb_node_service_up{node="node2"} 1

**Comment by nemmyam** [comment]
Also I just realized from the grafana dashboard you provided (nice work btw!) the $node variable in queries which made me understand you assume running the exporter from the actual node in the couchbase cluster but in our case I have a seperate couchbase cluster and I installed only the exporter as a deployment in a different kubernetes cluster
